const Actions = {
  SET_WEEK_FROM_INDEX: 'SET_WEEK_FROM_INDEX',
  SET_WEEK_FROM_DATE: 'SET_WEEK_FROM_DATE',
  UPDATE_BUDGET: 'UPDATE_BUDGET',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  UPDATE_ITEM: 'UPDATE_ITEM',
  ADD_WEEK: 'ADD_WEEK',
  SET_STATE: 'SET_STATE'
}

export default Actions;