const Actions = {
  SET_WEEK: 'SET_WEEK',
  UPDATE_BUDGET: 'UPDATE_BUDGET',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  UPDATE_ITEM: 'UPDATE_ITEM',
  ADD_WEEK: 'ADD_WEEK'
}

export default Actions;